openapi: 3.0.3
info:
  title: 'MyBetFund Admin'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/auth/get-otp:
    post:
      summary: ''
      operationId: postApiAuthGetOtp
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone_number:
                  type: string
                  description: ''
                  example: officia
                password:
                  type: string
                  description: ''
                  example: voluptatibus
              required:
                - phone_number
                - password
      security: []
  /api/auth/register:
    post:
      summary: ''
      operationId: postApiAuthRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone_number:
                  type: string
                  description: ''
                  example: vero
                password:
                  type: string
                  description: ''
                  example: soluta
                otp_code:
                  type: string
                  description: ''
                  example: et
                name:
                  type: string
                  description: ''
                  example: et
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: mcdermott.cristal@example.org
                state:
                  type: string
                  description: ''
                  example: blanditiis
              required:
                - phone_number
                - password
                - otp_code
                - name
                - email
                - state
      security: []
tags:
  -
    name: Endpoints
    description: ''
